export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL';

export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_COUNTRY = 'SET_COUNTRY';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_NEWS_URI = 'SET_NEWS_URI';
export const INCREMENT_PAGE_NUMBER = 'INCREMENT_PAGE_NUMBER';
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_SEARCH_FROM_DATE = 'SET_SEARCH_FROM_DATE';
export const SET_SEARCH_TO_DATE = 'SET_SEARCH_TO_DATE';
export const SET_NEWS_SORTBY = 'SET_NEWS_SORTBY';

export const SET_NEWS_SOURCES = 'SET_NEWS_SOURCES';
export const SET_NEWS_DOMAINS = 'SET_NEWS_DOMAINS';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const SAVE_ARTICLE_SUCCESS = 'SAVE_ARTICLE_SUCCESS';
export const GET_SAVED_ARTICLES_SUCCESS = 'GET_SAVED_ARTICLES_SUCCESS';
export const DELETE_SAVED_ARTICLE_SUCCESS = 'DELETE_SAVED_ARTICLE_SUCCESS';
